#!/usr/bin/env bash
# Ce script modifie les résolutions de localhost et facebook.com

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
